### ISSUE TITLE
[5.3.17] Issue with a view Rendering and the RenderingModel Sitecore class

### ISSUE THREAD

**Issue by sebmourier** [mikeedwards83/Glass.Mapper#373]
Last week I had an issue : https://github.com/mikeedwards83/Glass.Mapper/issues/371 and your last version fixed it.

Unfortunately your last version give me an error related to the LazyObjectInterceptor if I inspect my stacktrace.

```
[NullReferenceException]
   Castle.Proxies.RenderingModelProxy.get_Item_callback() +16
   Castle.Proxies.Invocations.RenderingModel_get_Item.InvokeMethodOnTarget() +39
   Castle.DynamicProxy.AbstractInvocation.Proceed() +109
   Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.LazyObjectInterceptor.Intercept(IInvocation invocation) in C:\TeamCity\buildAgent\work\9693a2d38f55a4a\Source\Glass.Mapper\Pipelines\ObjectConstruction\Tasks\CreateConcrete\LazyObjectInterceptor.cs:107
   Castle.DynamicProxy.AbstractInvocation.Proceed() +443
   Castle.Proxies.RenderingModelProxy.get_Item() +163
   ASP._Page_Views_Shared__BlocContenuFondGrisAvecCoinBouton_cshtml.Execute() in C:\Inetpub\wwwroot\IA\Website\Views\Shared\_BlocContenuFondGrisAvecCoinBouton.cshtml:10
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +251
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +147
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +121
   System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData) +135
   Sitecore.Mvc.Presentation.ViewRenderer.Render(TextWriter writer) +314

[InvalidOperationException: Error while rendering view: '/Views/Shared/_myView.cshtml' (model: 'Castle.Proxies.RenderingModelProxy, DynamicProxyGenAssembly2').
]
```

Model.Item (of type RenderingModel) throw an exception in my view.

This was not the case with the version 5.3.15.

**Comment by mikeedwards83** [comment]
Can you give me and example of the model/code you are using?

**Comment by sebmourier** [comment]
The model is the RenderingModel class from the Sitecore library "Sitecore.Mvc.dll" (version 8.2.170728 - aka v8.2.5)

I use this class in a cshtml view with the following code :   

```
@model RenderingModel

@{
    var serviceSitecore = new SitecoreService(global::Sitecore.Context.Database);
    
    MyModel item = serviceSitecore.GetItem<MyModel>(Model.Item);
}
```
I give you the content of MyModel class but IMO that's not the problem. The problem is really when I access the property Item of the Sitecore class RenderingModel

```
public class MyModel
{
	public virtual Image Property1 { get; set; }
	public virtual string Property2  { get; set; }
	public virtual string Property3  { get; set; }
	public virtual string Property4  { get; set; }
	public virtual string Property5  { get; set; }
	public virtual Link Property6  { get; set; }
	public virtual Image Property7  { get; set; }
	public virtual string Property8  { get; set; }
	public string Property9  { get; set; } // this property has nothing to do with Sitecore
}
```

**Comment by sebmourier** [comment]
I can add some informations : 
In another view, I don't use the glass API to retreive data from Sitecore DB and instead I use the Sitecore API like that : 
```
<div class="class1">
    @if (!Model.Item["Title"].IsEmpty())
    {
        <h1>@Model.Item["Title"]</h1>
    }
....
</div>

And the same problem occurs so it's definitevly not linked to a Glass class model

**Comment by sud33p** [comment]
Hi,

We are getting the same issue. We downgraded to 5.3.15 but unfortunately looks like Glass is still trying to construct the object for `RenderingModel` as I can see this in the stack trace:

`[InvalidOperationException: Error while rendering view: '/Views/Common/Section.cshtml' (model: 'Castle.Proxies.RenderingModelProxy, DynamicProxyGenAssembly2')`

 This wasn't happening in v4 as everything was working fine until we upgraded to Sitecore 9.1 and Glass to >= v5.3.15. 

Further investigation revealed the `GetModelFromView` processor was causing this. Removing this processor will cease the exception:

```
<mvc.getModel>
        ...
        <processor type="Glass.Mapper.Sc.Pipelines.Response.GetModelFromView, Glass.Mapper.Sc.Mvc"
                   patch:before="*[@type='Sitecore.Mvc.Pipelines.Response.GetModel.GetFromItem, Sitecore.Mvc']" />
      </mvc.getModel>
```

But this is not a proper fix. Any idea what has changed in v5 that's causing this?

**Comment by sebmourier** [comment]
Hi,

Thanks sud33p, removing this processor resolves my issue.

However, as you said, this processor is here for a reason and I don't like removing it  (because of unknown side effects).

Your post makes me look after the LazyObjectInterceptor class and I debugged a litlle bit the debug.
What I found is that the property Item of the class RenderingModel has PropertyInfo.CanWrite = false.
There's a difference between the 2 versions (5.3.15 and 5.3.17) in the LazyObjectInterceptor : 
5.3.15 : PropertyInfo.CanWrite is not tested and the value of the property Item is retrieved (and the rest of the execution is correct)
5.3.17 : PropertyInfo.CanWrite is tested. The consequences are that the property Item of the class RenderingModel is not retrieved.

**Comment by dsimoes** [comment]
Hi,

I'm using Sitecore 9.1 habitat solution, and when I installed and enabled the latest Glass version, all hell breaks loose.

All views that use Sitecore.Mvc.Presentation.RenderingModel will trigger this exception:

   at Castle.Proxies.RenderingModelProxy.get_Item_callback()
   at Castle.Proxies.Invocations.RenderingModel_get_Item.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Glass.Mapper.Pipelines.ObjectConstruction.Tasks.CreateConcrete.LazyObjectInterceptor.Intercept(IInvocation invocation) in C:\TeamCity\buildAgent\work\9693a2d38f55a4a\Source\Glass.Mapper\Pipelines\ObjectConstruction\Tasks\CreateConcrete\LazyObjectInterceptor.cs:line 107
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RenderingModelProxy.get_Item()


If I remove the GetModelFromView processor, It will work.

Is there any solution for this?

Thanks very much.

**Comment by mikeedwards83** [comment]
Hi,

I have pushed a fix into the develop branch. I will create a release later today to fix this issue.

Thanks

Mike

**Comment by mikeedwards83** [comment]
In release 5.4.21

**Comment by MinyieDiaz** [comment]
Hi! I am using 5.4.21 with SC 9.1.1 and still getting the same issue.
